server:
  context-path: /console
debug: false
spring:
  application:
    name: and-console
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/and?useUnicode=true&amp;characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
  activiti:
    process-definition-location-prefix: classpath*:/processes/
  mvc:
    favicon:
      enabled: true
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations:
  - classpath:/mapper/*.xml
flyway:
  enabled: false